name: PR-Merge
on: 
  pull_request:
    types: [opened, closed]

jobs:
  merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ECHO
        run: |
          echo ${{ github.event.pull_request.merged }}
          echo $GITHUB_REF
          echo $GITHUB_SHA
      - if: github.event.pull_request.merged == true
        name: MERGED
        run: |
          echo $GITHUB_REF
          echo $GITHUB_SHA
          filename=$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32)
          touch $filename
          git add -A
          git commit -m "Test"
          git push
          
