name: PR-Merge
on: 
  pull_request:
    types: [closed]

jobs:
  merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: touch new file
        run: |
          touch $(date +%s)
      - if: github.event.pull_request.merged == true
        name: Push commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]'"
          git add -A
          git commit -m "TEST BY BOT"
          git push
          
