name: PR-Merge
on: 
  pull_request_target:
    types: closed

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - if: github.event.pull_request.merged == 'true'
        name: Test
        run: |
          echo $GITHUB_REF
          echo $GITHUB_SHA
          
